### ISSUE TITLE
Custom comment formatting in ESLint

### ISSUE THREAD

**Issue by davidgatti** [0x4447/eslint-plugin-0x4447#2]
Regarding the commend, each commend always have a "header" and footer regardless of how many lines are in the middle. And this two section are just an empty `//` comment, and this is the bare minimum, then ideal it be nice if we can check that between `//` and the words there is a Tab, and like wise, there is a tab between the `1.` and the word (the number and the word)

```
//empty line
//tab1.tabHello
//empty line
```

**Comment by Jarmahent** [comment]
@davidgatti So after literally days of trying to get this eslint rule to work. I have come to a very big conclusion.

Writing this Eslint rule has definitely proven to be a challenge, this is because of how comments are characterized in AST. Comments are stored in an array and checking if comments are in blocks definitely proves to be a challenge. 
I say this because there are too many edge cases to deal with working with this array. 

The only way of making sure that a comment block has padding is to make sure that these comments are of type `block`

`// this is a comment line`

`/*  This is a comment block */`

With a comment block it is easy to create an eslint rule to check for padding because I can check inside of the value of the comment block and check if there are new lines at the beginning and end of the block so:

```
/*
 Good padded comment
*/
```

```
/* Bad
padded comment
*/
```

With `/**/` comments its way easier to tell if a comment has padding or not. But with single line comments its definitely way harder. Not impossible but it will take quite long.

**Comment by davidgatti** [comment]
@Jarmahent ok, this is good work, sometimes some things are not worth pursuing. Since your code is here in the future I might give it a try.
